"""empty message

Revision ID: 1387bf5c4b0d
Revises: 
Create Date: 2025-10-23 11:04:29.720919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '1387bf5c4b0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('official_link', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_vacansies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technology_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_of_obligation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancies_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workmodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('compensation_min', sa.Integer(), nullable=True),
    sa.Column('compensation_max', sa.Integer(), nullable=True),
    sa.Column('workload', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workload'], ['workloads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacansies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('raw_vacansy_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('speciality_id', sa.Integer(), nullable=True),
    sa.Column('workmode', sa.Integer(), nullable=True),
    sa.Column('workload', sa.Integer(), nullable=True),
    sa.Column('compensation_min', sa.Integer(), nullable=True),
    sa.Column('compensation_max', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raw_vacansy_id'], ['raw_vacansies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workload'], ['workloads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workmode'], ['workmodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('speciality_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('speciality_id', sa.Integer(), nullable=True),
    sa.Column('vacansy_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('employment_at', sa.DateTime(), nullable=False),
    sa.Column('dismissal_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vacansy_id'], ['vacansies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancy_speciality_experiences',
    sa.Column('speciality_id', sa.Integer(), nullable=False),
    sa.Column('vacansy_id', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Float(), nullable=False),
    sa.Column('type_of_obligation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_of_obligation_id'], ['type_of_obligation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vacansy_id'], ['vacansies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('speciality_id', 'vacansy_id')
    )
    op.create_table('vacansies_languages',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('vacansy_id', sa.Integer(), nullable=False),
    sa.Column('type_of_obligation_id', sa.Integer(), nullable=True),
    sa.Column('language_level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_level_id'], ['language_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_of_obligation_id'], ['type_of_obligation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vacansy_id'], ['vacansies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('language_id', 'vacansy_id')
    )
    op.create_table('vacansies_technologies',
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('vacansy_id', sa.Integer(), nullable=False),
    sa.Column('type_of_obligation_id', sa.Integer(), nullable=True),
    sa.Column('technology_level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_level_id'], ['technology_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_of_obligation_id'], ['type_of_obligation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vacansy_id'], ['vacansies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('technology_id', 'vacansy_id')
    )
    op.create_table('worker_skills',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('technology_level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_level_id'], ['technology_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('worker_id', 'technology_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_skills')
    op.drop_table('vacansies_technologies')
    op.drop_table('vacansies_languages')
    op.drop_table('vacancy_speciality_experiences')
    op.drop_table('experience_workers')
    op.drop_table('workers')
    op.drop_table('vacansies')
    op.drop_table('resumes')
    op.drop_table('languages_levels')
    op.drop_table('workmodes')
    op.drop_table('workloads')
    op.drop_table('vacancies_sources')
    op.drop_table('users')
    op.drop_table('type_of_obligation')
    op.drop_table('technology_levels')
    op.drop_table('technologies')
    op.drop_table('specialities')
    op.drop_table('raw_vacansies')
    op.drop_table('languages')
    op.drop_table('language_levels')
    op.drop_table('companies')
    # ### end Alembic commands ###
